### ISSUE TITLE
Search Engine for publications

### ISSUE THREAD

**Issue by itellaetxe** [ifiriondo/BilbaoLab#1]

**Comment by ifiriondo** [comment]
Bibbase berak daka aukera searcher bat gehitzeko. showSearch=1 jarrita
# Publications.md 

<div id="publications-bibbase">
  <script src="https://bibbase.org/show?bib=https://raw.githubusercontent.com/ifiriondo/BilbaoLab/master/_data/biblio.bib&jsonp=1**&showSearch=1**"></script>
</div>

**Comment by ifiriondo** [comment]
hemen dokumentazioa: https://bibbase.org/blog/new-feature-search-filter-bar
